app = 'flypervisor'
primary_region = 'iad'

machine_config = '{ "containers": [{ "name": "app" }] }'
kill_timeout = 15

[env]
  DIST = 'ubuntu'
  RELEASE = 'resolute'

[mounts]
  source = 'data'
  destination = '/data'

[[services]]
  protocol = 'tcp'
  internal_port = 22
  auto_stop_machines = 'off'
  auto_start_machines = false

  [[services.ports]]
    port = 22

# [[services]]
#   protocol = 'tcp'
#   internal_port = 8080
#   auto_stop_machines = 'off'
#   auto_start_machines = false
#
#   [[services.ports]]
#     port = 80
#     handlers = ['http']
#     force_https = true
#
#   [[services.ports]]
#     port = 443
#     handlers = ['tls', 'http']

# [[services]]
#   protocol = 'udp'
#   internal_port = 53
#   auto_stop_machines = 'off'
#   auto_start_machines = false
#
#   [[services.ports]]
#     port = 53

[[vm]]
  cpu_kind = 'performance'
  cpus = 16
  memory_mb = 65536
