#!/bin/sh

if ! lxc-info -n dom0 -s 2> /dev/null | grep -q RUNNING
then
    echo "dom0 is not running" >&2
    exit 1
fi

# lxc-attach keeps the cwd if the same path exists inside the container
cd "$HOME" 2> /dev/null || cd /

set -- lxc-attach -n dom0 --clear-env \
    --set-var TERM="${TERM:-xterm}" \
    --set-var HOME="$HOME" \
    --set-var LANG="${LANG:-C.UTF-8}" \
    --set-var PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    --

case "$SSH_ORIGINAL_COMMAND" in
"")
    if test -t 0
    then
        # this is a pretty gross hack. login vhangup()s the pty provided by
        # lxc-attach, closes its fds, and reopens the pty itself. lxc-attach
        # sometimes notices the brief period where nothing holds the pty open
        # and drops the session. Use fd 3 to keep it open until login exits,
        # and catch any SIGHUPs.
        exec "$@" /bin/sh \
            -c 'trap : HUP; exec 3<&0; login -f root 3<&-; exit $?'
    fi
    exec "$@" su -l
    ;;
internal-sftp|*sftp-server*) exec "$@" /usr/lib/openssh/sftp-server ;;
*) exec "$@" /bin/sh -c "$SSH_ORIGINAL_COMMAND" ;;
esac
